### ISSUE TITLE
수박게임 공용 TODO(1) #1

### ISSUE THREAD

**Issue by gisu1102** [INU-Fake-Developers/gisu1102-WatermelonGame#1]
-  Webstorm 설치

- [ ]  수박게임 오리지널 플레이해보기

- [ ]  수박게임 코드 클론(포크)하기

- [ ]  수박게임 제작의도(덕질, 기념일, 친목도모 등) 선정

- [ ]  이미지 고르기
